version: '3.8'
services:
  backend:
    image: imsongj/test_backend
    build:
      context: ./backend/lighthouse
      dockerfile: Dockerfile

  frontend:
    image: imsongj/test_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile